### ISSUE TITLE
Add Architect as Career Path

### ISSUE THREAD

**Issue by husyn** [Software-Development-Pakistan/Software-Development-Pakistan.github.io#51]
### Problem

There is a well known career path of Architect, which is missing from the list available today. There are few types of Architect roles like Solutions Architect, Enterprise Architect, etc. But basic details should be available to begin with.

### Solution
Create a new Career Path named **Architect**

### Alternatives
Alternatively add the progression steps in each career path towards Architect or Principal Engineer. For e.g.: Data Engineering Architect is a very senior role in Data Engineering umbrella. Same goes with Cloud Development, IoT, etc. But a separate career path is a clear and obvious solution.

**Comment by Rubix982** [comment]
Good suggestion! 
Let me quickly make a simple file for it.

**Comment by Rubix982** [comment]
I think the best way, since this is a pretty big change, would be to have a branch of this on its own.
I created the file, made an entry into the table of contents, and filled `architect/index.md` with the basic template - removing some obvious headers.

The branch is here, https://github.com/Software-Development-Pakistan/Software-Development-Pakistan.github.io/tree/career-path-architect

**Comment by husyn** [comment]
Linked PR: https://github.com/Software-Development-Pakistan/Software-Development-Pakistan.github.io/pull/55
